#!/usr/bin/env python3
import os
import sys
import requests

for slug in sys.argv[1:]:
    url = f"https://www.portugalrunning.com/eventos/{slug}"
    page_path = os.path.join("events", slug, "page.html")
    if os.path.exists(page_path):
        continue
    response = requests.get(url)
    response.raise_for_status()
    with open(page_path, "w") as f:
        f.write(response.text)

